'use client'
import Navbar from '@/components/layout/nav'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Buuk Me Now',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><Navbar />
        <div className='bg-[#F3F3F4]'>{children}</div>

      </body>
    </html>
  )
}
